improve release action

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,30 +7,30 @@ on:
 
 jobs:
   release:
-    name: Create release
+    name: Create Release
     runs-on: macos-latest
     permissions: write-all
     outputs:
       upload_url: ${{ steps.create_release.outputs.upload_url }}
     steps:
-      - name: Extract version name
+      - name: Extract Version Name
         id: extract_name
         run: echo "name=$(echo ${GITHUB_REF##*/})" >>$GITHUB_OUTPUT
         shell: bash
 
-      - name: Checkout to push branch
+      - name: Checkout to Push Branch
         uses: actions/checkout@v4
         with:
           ref: ${{ github.ref }}
           fetch-depth: 0
 
-      - name: Generate changelog
+      - name: Generate Changelog
         id: changelog
         uses: metcalfc/changelog-generator@v4.1.0
         with:
-          myToken: ${{ secrets.GITHUB_TOKEN }}
+          mytoken: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Create release
+      - name: Create Release
         id: create_release
         uses: ncipollo/release-action@v1
         with:
@@ -38,25 +38,46 @@ jobs:
           body: ${{ steps.changelog.outputs.changelog }}
 
   publish:
-    name: Publish release
+    name: Publish Release
     permissions: write-all
     runs-on: macos-latest
     needs: release
     steps:
-      - name: Checkout to push branch
+      - name: Checkout to Push Branch
         uses: actions/checkout@v4
         with:
           ref: ${{ github.ref }}
           fetch-depth: 0
 
-      - name: Extract version from tag
+      - name: Extract Version from Tag
         uses: damienaicheh/extract-version-from-tag-action@v1.1.0
+
+      - name: Gradle Wrapper Validation
+        uses: gradle/actions/wrapper-validation@v3
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: 17
           distribution: 'corretto'
+
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v3
+        with:
+          gradle-home-cache-cleanup: true
+
+      - name: Confirm Tag Version Matches Properties Version
+        shell: bash
+        run: |
+          PROPERTIES="$(./gradlew properties --console=plain -q)"
+          PROPERTIES_VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
+
+          if [ "$TAG_VERSION" != "$PROPERTIES_VERSION" ]; then
+            echo "Error: TAG_VERSION ($TAG_VERSION) != PROPERTIES_VERSION ($PROPERTIES_VERSION)"
+            exit 1
+          fi
+        env:
+          TAG_VERSION: ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}
 
       - name: Publish to MavenCentral
         run: ./gradlew publishAllPublicationsToSonatypeRepository
